# Generated by Django 5.2.1 on 2025-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(default='', upload_to='Category_covers/', verbose_name='Image de couverture'),
            preserve_default=False,
        ),
    ]
