# Generated by Django 5.2.1 on 2025-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_tag_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag_new_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default='new', max_length=50, null=True, verbose_name='Tag du produit'),
        ),
    ]
